### ISSUE TITLE
Error(s) causing truncated data set for WGS tab

### ISSUE THREAD

**Issue by magnulei** [NorwegianVeterinaryInstitute/shinylims#8]
Getting this error when the Run ID hasnt been set yet for a sequencing run:

2024-10-11 12:00:21,072 [ERROR] [shiny_sample_table_WGS.py:89] - Uncaught exception: TypeError: expected string or bytes-like object
Traceback (most recent call last):
  File "/opt/gls/clarity/customextensions/shiny_app/shiny_sample_table_WGS.py", line 465, in <module>
    create_csv_file( )
  File "/opt/gls/clarity/customextensions/shiny_app/shiny_sample_table_WGS.py", line 386, in create_csv_file
    match = re.match(r"^\d{6}_[A-Z]+\d+", runID)
  File "/usr/lib64/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

Here the error is probably just that we are trying to do regular experession on a None value. 

However, I also see that even though the csv data file for samples is 1488 lines long (at the moment), only 1138 entries are shown in the shiny app table, So we are missing 350 values for some reason. No error is found in the log file to explain this. In theory the table should simply display everything from the csv file! Needs to be investigated asap!

edit: found the most likely culprit for the ca 350 missing values. There are samples in the csv file missing received date. All from Solveig Mo (Gensurv project). Probably has a logical explanation.... to be continued.

FYI, @CathrineAB

**Comment by magnulei** [comment]
The 350 samples missing from the table are indeed pending projects:

![image](https://github.com/user-attachments/assets/2d25ff0a-fca2-44ff-a60d-61b24077f008)

**Comment by magnulei** [comment]
Issue solved!

-TypeError solved by adding a type-check before doing the re match.
-Pending projects and associated samples are now included in the tables (incuded na-values in the filtering steps)

See above commits for details.

Closing issue

FYI, @CathrineAB
